export function languageToExtension(language: string): string {
  const map: Record<string, string> = {
    javascript: "js",
    typescript: "ts",
    python: "py",
    java: "java",
    c: "c",
    "c++": "cpp",
    cpp: "cpp",
    csharp: "cs",
    "c#": "cs",
    ruby: "rb",
    go: "go",
    rust: "rs",
    php: "php",
    swift: "swift",
    kotlin: "kt",
    scala: "scala",
    dart: "dart",
    html: "html",
    css: "css",
    scss: "scss",
    less: "less",
    json: "json",
    yaml: "yml",
    yml: "yml",
    markdown: "md",
    md: "md",
    shell: "sh",
    bash: "sh",
    powershell: "ps1",
    sql: "sql",
    r: "r",
    perl: "pl",
    lua: "lua",
    objectivec: "m",
    "objective-c": "m",
    xml: "xml",
    vue: "vue",
    svelte: "svelte",
    jsx: "jsx",
    tsx: "tsx",
    plaintext: "txt",
    text: "txt",
  };

  return map[language.toLowerCase()] || "";
}
